
import type { Metadata } from "next";
import { Header } from "@/components/ui/header/Header";
import { Footer } from "@/components/ui/footer/Footer";


export const metadata: Metadata = {
  title: "week-4-react-2-classwork",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

     <body>
        <Header />
        <main >
          {children}
        </main>
        <Footer />
      </body>

    </html>
  )
}
