<<<<<<< HEAD
import type { Metadata } from "next";
import { Header } from "@/components/ui/header/Header";
import { Footer } from "@/components/ui/footer/Footer";


export const metadata: Metadata = {
  title: "week-4-react-2-classwork",
  description: "Generated by create next app",
};
=======
export const metadata = {
  title: 'week-4-react-2-classwork',
  description: 'Generated by Next.js',
}
>>>>>>> 0c11302055c7c07a7da46e03fd0c73ec101becd2

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
     <body>
        <Header />
        <main >
          {children}
        </main>
        <Footer />
      </body>
=======
      <body>{children}</body>
>>>>>>> 0c11302055c7c07a7da46e03fd0c73ec101becd2
    </html>
  )
}
